# Generated by Django 3.2.8 on 2021-10-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('PhoneNo', models.IntegerField(max_length=15)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SpamUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('PhoneNo', models.IntegerField(max_length=15)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
