# Generated by Django 3.2.8 on 2021-10-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpamByterApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spamusers',
            name='password',
        ),
    ]
