# Generated by Django 3.2.8 on 2021-10-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpamByterApp', '0002_remove_spamusers_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genusers',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='spamusers',
            name='Name',
        ),
    ]
