# Generated by Django 3.2.8 on 2021-10-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpamByterApp', '0003_auto_20211028_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genusers',
            name='PhoneNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spamusers',
            name='PhoneNo',
            field=models.IntegerField(),
        ),
    ]
