# Generated by Django 3.2.8 on 2021-10-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpamByterApp', '0004_auto_20211028_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamusers',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
