# Generated by Django 3.1.4 on 2021-10-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpamByterApp', '0007_alter_spamusers_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genusers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spamusers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
